# https://github.com/compose-spec/compose-spec/blob/master/spec.md
version: "3.8"
services:
  ink:
    container_name: ink
    image: ink:latest
    # view memory usage with `docker stats`
    # cpus: 0.75
    # mem_reservation: '125M'
    # mem_limit: '750M'
    # https://docs.docker.com/compose/compose-file/compose-file-v3/#resources
    # requires use of `docker-compose --compatibility ...`
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 2
        window: 120s
      resources:
        limits:
          cpus: '0.75'
          memory: 750M
        reservations:
          cpus: '0.125'
          memory: 125M
    # restart: always
    build:
      context: "."
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
      - "9933:9933"
      - "9944:9944"
      - "9615:9615"
      - "30333:30333"
      - "3000:3000"
      - "443:443"
      - "80:80"

    # expose all ports from docker container
    network_mode: host
    env_file:
      - .env
