version: "3.8"
services:
  ink:
    container_name: ink
    image: ink:latest
    restart: always
    build:
      context: "."
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
      - "9933:9933"
      - "9944:9944"
      - "30333:30333"
    env_file:
      - .env
