version: "3.8"
services:
  ink-python:
    container_name: ink-python
    image: ink-python:latest
    # view memory usage with `docker stats`
    # cpus: 1
    mem_reservation: '125M'
    mem_limit: '750M'
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 2
        window: 120s
      resources:
        limits:
          cpus: '0.75'
          memory: 750M
        reservations:
          cpus: '0.125'
          memory: 125M
    build:
      context: "../../"
      dockerfile: ./docker/ink-python/DockerfilePython
    # keep container running and just execute commands inside
    stdin_open: true
    tty: true
    volumes:
      - ../../:/app
    env_file:
      - ../../.env